project_id = "kwbbkvfudrzznrhoumej"

[functions.send-whatsapp-invoice]
verify_jwt = false

[functions.invoice-og]
verify_jwt = false

[functions.woo-sync-products]
verify_jwt = false

[functions.woo-sync-orders]
verify_jwt = false

[functions.woo-sync-stock]
verify_jwt = false

[functions.woo-webhook]
verify_jwt = false

[functions.payu-hash]
verify_jwt = false

[functions.payu-verify]
verify_jwt = false

[functions.guest-checkout]
verify_jwt = false

[functions.shiprocket]
verify_jwt = false
